# Generated by Django 3.2.6 on 2022-01-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
