# Generated by Django 3.2.6 on 2022-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
