# Generated by Django 3.2.6 on 2022-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_class_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.CharField(max_length=255)),
                ('matricNo', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('class_docfile', models.FileField(upload_to='')),
            ],
        ),
    ]
