# Generated by Django 3.2.6 on 2022-01-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_class_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_fileupload',
            name='class_filedata',
            field=models.TextField(null=True),
        ),
    ]
